name: flutter_widgets
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10 #svg图片(MIT)
  cupertino_icons: ^1.0.2
  file_picker: ^8.0.5 #图片文档选择
  connectivity_plus: ^6.0.4 #网络检查
  dio: ^5.5.0+1 #dio网络请求
  path_provider: ^2.1.4 #文件目录操作
  oktoast: ^3.4.0 #toast土司提示
  contained_tab_bar_view: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
